platform :ios, '9.0'
target 'AMDaliy' do
#use_frameworks!
pod 'FMDB'
pod 'AFNetworking', '~> 3.0'
pod 'ZFPlayer', '~> 3.0'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
pod 'ZFPlayer/ijkplayer', '~> 3.0'

end
